### ISSUE TITLE
ESP_Esay_Netscan only showing IP

### ISSUE THREAD

**Issue by goldriver2** [Grovkillen/ESP_Easy_Netscan#1]
I tried the tool and on my environnmrnt it only show the IP, the name, number etc... are not displayed
![esp1](https://user-images.githubusercontent.com/7215561/36340165-f6c223cc-13a4-11e8-8d3c-2adc30e3579f.PNG)

windows 10

espeasy :
Build: | 20000 - Mega
Plugin sets: | [Normal]
Number of Plugins: | 44
Core Version: | 2_4_0
Flash Size: | 4096 kB
Flash Writes (daily/boot): | 2 / 2
Sketch Size/Free: | 586 kB / 2484 kB

![esp2](https://user-images.githubusercontent.com/7215561/36340184-885f7168-13a5-11e8-910f-6a6f4f50850f.PNG)

**Comment by Grovkillen** [comment]
It's a bit ahead of time, only as of now the json page is occupied with these values.

**Comment by Grovkillen** [comment]
Please update to latest.
