### ISSUE TITLE
Tool function and used font

### ISSUE THREAD

**Issue by themanfrommoon** [Grovkillen/ESP_Easy_Netscan#2]
Hello Grovkillen,

1. What does the tool search and find really?
Because it does not only find ESPEasy installations on ESP8266 Boards.
It also finds my ESP8266 Boards which I flashed with my own Sketches with Arduino IDE.
So it is not an ESPEasy Scanner rather than an ESP8266 (or whatever) Scanner?!

2. The used font is very strange If you are used to work with Windows. Why don't you use one of the windows standard fonts? I would really prefer a standard font.

Best regards,
Chris

**Comment by yiit** [comment]
Please can you give me open sources code email yiitozduner@gmail.com

**Comment by Grovkillen** [comment]
1. I scan for Espressif units
2. I really like the font and will probably not change it since this is a very crude and basic tool that I will not maintain once we integrate this into the ESP Easy GUI (which I intend on doing this upcoming autumn).
